#!/usr/bin/env bash

switch_to() {
    if [[ -z $TMUX ]]; then
        tmux attach-session -t $1
    else
        tmux switch-client -t $1
    fi
}

has_session() {
    tmux list-sessions | grep -q "^$1:"
}


if [[ $# -eq 1 ]]; then
    if [[ $1 == '.' ]]; then
        selected="$(ls|fzf)"
    else
        selected=$1
    fi
else
    selected="$(tmux ls -F \#{session_name} | fzf)"
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
echo $selected
tmux_running=$(pgrep tmux)

tmux new-session -ds $selected_name -c $selected 

switch_to $selected_name
