#! bin/bash

if [ ! -d "$HOME/.dotfiles/" ]; then
    echo "no .dotfiles"
    exit 1
fi

$HOME/.dotfiles/mklinks

# Update and Basic
echo "installing apps ------------------------------------------------------------------------------------------------------------------------------------"
sudo apt update
sudo apt install -y curl git zsh bat tmux neofetch

echo "changing shell ------------------------------------------------------------------------------------------------------------------------------------"
# zsh
sudo chsh -s $(which zsh)

echo "installing Firefox ------------------------------------------------------------------------------------------------------------------------------------"
# Firefox
sudo install -d -m 0755 /etc/apt/keyrings
wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | sudo tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null
echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | sudo tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null
echo '
Package: *
Pin: origin packages.mozilla.org
Pin-Priority: 1000
' | sudo tee /etc/apt/preferences.d/mozilla 
sudo apt-get update && sudo apt-get install firefox

echo "installing Homebrew------------------------------------------------------------------------------------------------------------------------------------"
# Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

echo "Configuring zsh ------------------------------------------------------------------------------------------------------------------------------------"
# zsh finish
brew install jandedobbeleer/oh-my-posh/oh-my-posh
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
oh-my-posh font install
source $HOME/.zshrc

echo "Configuring nvim ------------------------------------------------------------------------------------------------------------------------------------"
# nvim setup
brew install neovim
git clone --depth 1 https://github.com/wbthomason/packer.nvim\\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
nvim --headless -c 'luafile ~/.config/nvim/lua/ancientherox/packer.lua' -c 'PackerSync' -c 'qa'

# Lastly
echo "log out and back in and add 'Hack' font to terminal"
