#! /usr/bin/bash

LOCK_FILE="$HOME/.cache/eww-calendar.lock"
EWW_BIN="$HOME/.local/bin/eww"

run() {
  ${EWW_BIN} open calendar
}
if [[ ! -f "$LOCK_FILE" ]]; then
  touch "$LOCK_FILE"
  run
else
  ${EWW_BIN} close calendar
  rm "$LOCK_FILE"
fi
