#! /usr/bin/bash

LOCK_FILE="$HOME/.cache/eww-wifi.lock"
EWW_BIN="$HOME/.local/bin/eww"

run() {
  nets=$(/home/eduardglez/.config/eww/scripts/wifidata networks)
  echo $nets
  ${EWW_BIN} update networks="[]"
  ${EWW_BIN} update networks="${nets}"
  ${EWW_BIN} open wifi-window 
}
if [[ ! -f "$LOCK_FILE" ]]; then
  touch "$LOCK_FILE"
  run
else
  ${EWW_BIN} close wifi-window
  rm "$LOCK_FILE"
fi
